### ISSUE TITLE
ZetArtifacts Multitudes Compatibility

### ISSUE THREAD

**Issue by William758** [Moffein/FixPlayercount#1]
https://github.com/William758/ZetArtifacts/issues/7

ZetArtifacts has a config to disable or always enable an artifact effect. So if the setting is ever changed then the artifact def is never created and causes a NRE. You can instead use the ZetMultifact.Enabled property to check if it's active.

**Comment by Moffein** [comment]
Got it, gonna upload a fix for this in a bit.

**Comment by Moffein** [comment]
Update is out, this should be fixed now.
